### ISSUE TITLE
Anytime I try to spawn in a modded iron golem. Another one of my mods "Performant" kicks the entity. It looks like the effects your mod gives iron golems is causing them to get kicked out. 

### ISSUE THREAD

**Issue by Minebrah** [superlord9362/Incense#1]
[13Apr2023 14:31:42.461] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:126) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Apr2023 14:31:42.464] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:129) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Apr2023 14:32:18.769] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:126) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Apr2023 14:32:18.772] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:129) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Apr2023 14:32:50.325] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:126) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13Apr2023 14:32:50.328] [Server thread/INFO] [com.performant.coremod.Performant/]: AI tried to add over 100 goals, removing entity
java.lang.Exception: Too many AI Tasks
	at com.performant.coremod.entity.ai.CustomGoalSelector.m_25352_(CustomGoalSelector.java:214) ~[performant-1.19.2-8.8.jar%231263!/:1.19.2-8.8]
	at superlord.incense.common.CommonEvents.onEntityEndRelaxation(CommonEvents.java:129) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at superlord.incense.common.__CommonEvents_onEntityEndRelaxation_LivingTickEvent.invoke(.dynamic) ~[incense-1.0.0-1.19.2.jar%231110!/:1.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:315) ~[forge-1.19.2-43.2.6-universal.jar%231502!/:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2251) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.Mob.m_8119_(Mob.java:406) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.entity.animal.IronGolem.m_8119_(IronGolem.java:1044) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:658) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.entity.TickOptimizer.handleGuardEntityTick(TickOptimizer.java:62) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.entity.TickOptimizer.entityTicking(TickOptimizer.java:50) ~[NoSeeNoTick-1.19.2-1.0.0.jar%231239!/:1.0.0-build.9999]
	at net.minecraft.world.level.Level.m_46653_(Level.java:2539) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:323) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:303) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%231497!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Minebrah** [comment]
Sorry For the sloppy Copy/paste here's a gist I made.

[https://gist.github.com/Minebrah/9509dffaf1ded069fd6dab182e72cced](url)
